### PR TITLE
Joomla 4.0.3 & 3.10.2

### PR DESCRIPTION
**Pull request by zero-24**
cc @Llewellynvdm can you please confirm that i replaced everything as expected?

### CODE REVIEW

**Comment by Llewellynvdm** [comment]
Some of these hash values are correct as the files must first exist for them to be made created.

image

This means only once the version has been release can we effectively build the new images. This will put the docker build after the release and not head of it. But this is better then trying to do this manually.

Since to push out the new images once the new versions are released on github, and on the Joomla API all we have to do here is update the versions-helper.json file and run `./update.sh` and that will do the rest of the work.

**Comment by zero-24** [comment]
> Since to push out the new images once the new versions are released on github, and on the Joomla API all we have to do here is update the versions-helper.json file and run ./update.sh and that will do the rest of the work.

Yes but calling the update.sh (after the release) should result into what i have done here right? Cause I like to prepare that PR upfront so we dont have to do that much work right after the release and as much as possible is prepared beforehand.

**Comment by Llewellynvdm** [comment]
At the moment it seems the release is in the API but not on github, and so the build fails.

**Comment by zero-24** [comment]
> At the moment it seems the release is in the API but not on github, and so the build fails.

What do you mean by "in the API"? Its right the release have not been published yet and yes its expected that the build fails for now.

> Some of these hash values are not correct as the files must first exist for them to be created.

Yes the packages have not been published yet.

**Comment by Llewellynvdm** [comment]
I think you are making things to complicated. The moment the release goes out, update the images... all I asked for is a heads-up. I think your missing how the system works, and that because your trying to make it do  something that is not part of the design.

**Comment by Llewellynvdm** [comment]
> What do you mean by "in the API"? Its right the release have not been published yet and yes its expected that the build fails for now.

For one... where does it get the new SHA512 values?

**Comment by zero-24** [comment]
> > What do you mean by "in the API"? Its right the release have not been published yet and yes its expected that the build fails for now.
> 
> For one... where does it get the new SHA512 values?

George and I have prepared the packages so we have the hashes already ;-)

**Comment by Llewellynvdm** [comment]
We can change the design, but really it is so easy... just update one file (versions-helper.json) and run `.update.sh` and it gets the hash automatically from the API.

**Comment by zero-24** [comment]
> I think you are making things to complicated. The moment the release goes out, I can update the images... all I asked for is a heads-up. I think your missing how the system works, and that because your trying to make it do  something that is not part of the design.

Fine for me. Next release is Tuesday, will close for now so you can update the images yourself.

**Comment by zero-24** [comment]
> We can change the design, but really it is so easy... just update one file (versions-helper.json) and run `.update.sh` and it gets the hash automatically from the API.

No need to change any design when its easier how its done right now its fine for me. In the past i prepared the PRs with the hashes when thats now replaced by someone else running the update.sh after the release its fine for me.

**Comment by Llewellynvdm** [comment]
> Fine for me. Next release is Tuesday, will close for now so you can update the images yourself.

Really not about doing it myself, its just to help and make the load less for you guys...

**Comment by zero-24** [comment]
> > Fine for me. Next release is Tuesday, will close for now so you can update the images yourself.
> 
> Really not about doing it myself, its just to help and make the load less for you guys...

Yes sorry that is what i mean. When you or someone else who understands docker more than me runs that script and does the PR against docker lib its one thing less I have to take care about. So its much appreciated :)

**Pull request closed without merging**
